<h1>Account Index</h1>
<nav class="sub-nav">
  <ul class="sub-nav_menu_list">


    <li class="sub-nav_menu_list_item first active"><a href="/dashboard/show/account">Account</a></li>
    <li class="sub-nav_menu_list_item"><a href="/dashboard/create/account">Create Account</a></li>
    <li class="sub-nav_menu_list_item"><a href="/dashboard/edit/account">Edit Account</a></li>
    <li class="sub-nav_menu_list_item"><a href="/dashboard/delete/account">Delete Account</a></li>




  </ul>
</nav>

<section class="manage account">

  <?php

if ($payload && $payload[1]) {
    if ($payload[1] == 'account') {
        switch ($payload[0]) {
            case 'show':
                include VIEW . 'dashboard/account/show.phtml';
                break;
            case 'edit':
                include VIEW . 'dashboard/account/edit.phtml';
                break;
                
            case 'delete':
                  
                include VIEW . 'dashboard/account/delete.phtml';
                break;
                  
            case 'create':
                include VIEW . 'dashboard/account/create.phtml';
                break;
              
            default:
                header("location: /dashboard");
                break;
        }
    }
}
  ?>
</section>