<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <title>Профессия Веб-разработчик | Модуль 38. Финальный проект</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link href="http://fonts.googleapis.com/css?family=Kreon" rel="stylesheet">
  <!-- <link href="https://fonts.googleapis.com/css2?family=Kreon:wght@400;700&display=swap" rel="stylesheet"> -->
  <link rel="stylesheet" href="/assets/css/style.css" />
  <script defer src="/assets/js/app.js"></script>
</head>

<body>
  <noscript>Ваш браузер не поддерживает JavaScript!</noscript>

  <div class="wrapper">
    <?php include LAYOUT . 'parts/header.phtml'; ?>
    <!-- <?php include LAYOUT . 'parts/aside.phtml'; ?>
    -->


    <main class="main">
      <?php include VIEW . $content_view; ?>
    </main>

    <!-- <?php include LAYOUT . 'parts/footer.phtml'; ?>
    -->

  </div>
</body>