<?php
namespace App\views\dashboard;

include_once VIEW.'auth/utils/formHandler.php';
use App\views\auth\utils;

if (!utils\getLoginStatus()) {
    header('location: /');
    exit;
}

$name = $_SESSION['username']; //receiving name field value in $name variable

$token = $_SESSION['token']; //receiving password field value in $password variable

echo "Welcome: $name, your token is: $token"; ?>
<aside class="aside">

  <nav class="aside_nav">
    <ul class="aside_nav_list">
      <li class="aside_nav_list_item"><a href="/dashboard/show/profile">Profile</a></li>
      <li class="aside_nav_list_item"><a href="/dashboard/show/account">Account</a></li>
    </ul>
  </nav>

</aside>

<section class="dashboard">
  <h1>Dashboard</h1>
  <?php
if ($payload && $payload[1]) {
    switch ($payload[1]) {
        case 'profile':
            include VIEW.'dashboard/profile/index.phtml';
            break;
        case 'account':
            include VIEW.'dashboard/account/index.phtml';
            break;

        default:
            header('location: /dashboard');
            break;
    }
}

?>
</section>