<?php
$action = $this->getAction();
// print($action);
?>

<!doctype html>
<html lang="en" class="h-100">

<head>
  <title>PHP Template |
    <?php echo(isset($this->page_title) ? $this->page_title : 'Home Page')?>
  </title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

  <!-- Convert this to an external style sheet -->
  <style>
    main>.container {
      padding: 60px 15px 0;
      margin-bottom: 5rem;
    }

    .sticky-footer {
      position: sticky;
      left: 0;
      bottom: 0;
      width: 100%;
    }
  </style>
</head>

<body class="d-flex flex-column h-100">

  <nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Fixed navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/home/contact">Contact Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/home/about">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/home/chat">Chat</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>



  <?php print($action);
