    <footer class="footer ">
      <aside class="footer-sidebar">
        <h3>Contacts</h3>
        <ul class="list">
          <li class="first">Tel: <a href="tel:+12345678910">+1(234)5678910</a></li>
          <li>github: <a href="https://github.com/skripkalisa">skripkalisa</a></li>
          <li class="last">email: <a href="mailto:skripkalisa@local.host">skripkalisa@local.host</a></li>
        </ul>
      </aside>
      <div class="footer-content">
        <h3>About Us</h3>
        <p>
          A company that can synthesize courageously will (eventually) be able to transition easily. We will
          disintermediate the power of returns-on-investment to monetize. Our end-to-end feature set is second to none,
          but our newbie-proof administration and simple configuration. That is a remarkable achievement taking into
          account this month's financial state of things! If all of this comes off as mixed-up to you, that's because it
          is! If you incentivize dynamically, you may also mesh iteravely. The capacity to enable perfectly leads to the
          awards page of the customer journey. Our infinitely reconfigurable feature set is unparalleled in the
          industry, but our C2C2C paradigms and easy configuration is usually considered a remarkable achievement taking
          into account this month's financial state of things!
        </p>
      </div>
      <div class="caption">
        <a href="/">Skripkalisa LLC</a> &copy; <span class="year">
          1970
        </span></a>
      </div>
    </footer>