    <header class="header">
      <div class="logo">
        <a href="/">Skripkalisa <span class="cms">LLC</span></a>
      </div>
      <nav class="navbar">
        <ul class="menu list">
          <li class="first active"><a href="/">Home</a></li>
          <li><a href="/admin">Admin</a></li>
          <li><a href="/merchant">Merchant</a></li>
          <li><a href="/webmaster">Web Master</a></li>

        </ul>
      </nav>
    </header>