<?php
include_once CORE  .'token.php';
include_once VIEW  .'auth/utils/formHandler.php';
login();

if (getLoginStatus()) {
    header("location: /home/profile");
    exit;
}
?>


<form action="<?php echo htmlspecialchars($_SERVER["REQUEST_URI"]);?>
" method="post">
  <table>
    <tr>
      <td>Email:</td>
      <td> <input type="email" name="email" /></td>
    </tr>
    <tr>
      <td>Password:</td>
      <td> <input type="password" name="password" /></td>
    </tr>
    <input type="hidden" name="token" value="<?=$token?>">
    <tr>
      <td colspan="2"><input type="submit" value="login" /> </td>
    </tr>
  </table>
</form>


<?php
include_once CORE  .'token.php';
$_SESSION["CSRF"] = $token;
