<?php

include_once CORE  .'token.php';

use App\views\auth\utils;

if (utils\HandleAuth::getLoginStatus()) {
    header("location: /dashboard");
    exit;
}
?>


<form id="login-form">

  <div class="form-control">
    <b> Enter E-mail: </b>
    <input type="text" name="email"
      value="<?php echo $entity->email ?? '' ;?>">
    <div class="form-control-feedback"></div>
  </div>

  <div class="form-control">
    <b> Enter Password: </b>
    <input type="password" name="password"
      value="<?php echo $entity->password ?? '' ;?>">
    <div class="form-control-feedback"></div>
  </div>
  <input type="hidden" name="token" value="<?=$token?>">

  <div class="form-control">
    <input class="form-check-input" type="checkbox" value="remember" id="flexCheckDefault" name="remember">
    <label class="form-check-label" for="flexCheckDefault">
      Remember me
    </label>
  </div>
  <input type="submit" value="Login" />

</form>


<?php

$_SESSION["CSRF"] = $token;
