<?php
include_once CORE  .'token.php';
// include_once VIEW  .'auth/utils/formHandler.php';
use App\views\auth\utils;

if (utils\HandleAuth::getLoginStatus()) {
    header("location: /dashboard");
    exit;
}

?>


<h1>Register</h1>

<form id="register-form">

    <div class="form-control">
        <b> Enter Username: </b>
        <input type="text" name="username"
            value="<?php echo $entity->username ?? '' ;?>">
        <div class="form-control-feedback"></div>
    </div>


    <div class="form-control">
        <b> Enter E-mail: </b>
        <input type="text" name="email"
            value="<?php echo $entity->email ?? '' ;?>">
        <div class="form-control-feedback"></div>
    </div>

    <div class="form-control">
        <b> Enter Password: </b>
        <input type="password" name="password"
            value="<?php echo $entity->password ?? '' ;?>">
        <div class="form-control-feedback"></div>
    </div>

    <div class="form-control">
        <b> Repeat Password: </b>
        <input type="password" name="password2"
            value="<?php echo $password2 ?? '' ;?>">
        <div class="form-control-feedback"></div>
    </div>


    <input type="hidden" name="token" value="<?=$token?>">

    <button type="submit" name="submit" value="Register">Register
    </button>

</form>
<?php
$_SESSION["CSRF"] = $token;
